#pragma once
#include "QString"
#include "SFML\Graphics.hpp"
#include "qfile.h"
#include "QtXml\qxml.h"
#include "QtXml\qdom.h"
#include "QDebug"
#include "QSize"
#include "QPainterPath"
#include <iostream>
#include <qstring>
#include "QPolygon"
#include <Eigen/Dense>
#include <qstring>
#include <QDebug>
#include <QDir>
